-- Script SQL para inserir habilidades faltantes da BNCC
-- Ensino Fundamental - Anos Iniciais
-- Gerado em: 16/12/2025 00:51:33
-- Total de habilidades a inserir: 242
-- Habilidades já cadastradas (removidas): 118

-- Códigos já cadastrados (não serão inseridos):
--   - EF01MA22
--   - EF02MA06
--   - EF02MA07
--   - EF02MA08
--   - EF02MA09
--   - EF02MA10
--   - EF02MA11
--   - EF02MA12
--   - EF02MA13
--   - EF02MA14
--   - EF02MA15
--   - EF02MA16
--   - EF02MA17
--   - EF02MA18
--   - EF02MA19
--   - EF02MA20
--   - EF02MA21
--   - EF02MA22
--   - EF02MA23
--   - EF03MA06
--   - EF03MA07
--   - EF03MA08
--   - EF03MA09
--   - EF03MA10
--   - EF03MA11
--   - EF03MA12
--   - EF03MA13
--   - EF03MA14
--   - EF03MA15
--   - EF03MA16
--   - EF03MA17
--   - EF03MA18
--   - EF03MA19
--   - EF03MA20
--   - EF03MA21
--   - EF03MA22
--   - EF03MA23
--   - EF03MA24
--   - EF03MA25
--   - EF03MA26
--   - EF03MA27
--   - EF03MA28
--   - EF04MA06
--   - EF04MA07
--   - EF04MA08
--   - EF04MA09
--   - EF04MA10
--   - EF04MA11
--   - EF04MA12
--   - EF04MA13
--   - EF04MA14
--   - EF04MA15
--   - EF04MA16
--   - EF04MA17
--   - EF04MA18
--   - EF04MA19
--   - EF04MA20
--   - EF04MA21
--   - EF04MA22
--   - EF04MA23
--   - EF04MA24
--   - EF04MA25
--   - EF04MA26
--   - EF04MA27
--   - EF04MA28
--   - EF05MA06
--   - EF05MA07
--   - EF05MA08
--   - EF05MA09
--   - EF05MA10
--   - EF05MA11
--   - EF05MA12
--   - EF05MA13
--   - EF05MA14
--   - EF05MA15
--   - EF05MA16
--   - EF05MA17
--   - EF05MA18
--   - EF05MA19
--   - EF05MA20
--   - EF05MA21
--   - EF05MA22
--   - EF05MA23
--   - EF05MA24
--   - EF05MA25
--   - EF01CI06
--   - EF02CI06
--   - EF02CI07
--   - EF02CI08
--   - EF03CI06
--   - EF03CI07
--   - EF03CI08
--   - EF03CI09
--   - EF03CI10
--   - EF04CI06
--   - EF04CI07
--   - EF04CI08
--   - EF04CI09
--   - EF04CI10
--   - EF04CI11
--   - EF05CI06
--   - EF05CI07
--   - EF05CI08
--   - EF05CI09
--   - EF05CI10
--   - EF05CI11
--   - EF05CI12
--   - EF05CI13
--   - EF05GE07
--   - EF05GE08
--   - EF05GE09
--   - EF05GE10
--   - EF05GE11
--   - EF05GE12
--   - EF05HI07
--   - EF05HI08
--   - EF05HI09
--   - EF05HI10

START TRANSACTION;

INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP12', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Ler e compreender com certa autonomia cantigas, letras de canção, dentre outros gêneros do campo da vida cotidiana, considerando a situação comunicativa e o tema/assunto do texto e relacionando sua forma de organização à sua finalidade.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP13', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Planejar e produzir bilhetes e cartas, em meio impresso e/ou digital, dentre outros gêneros do campo da vida cotidiana, considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP14', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Planejar e produzir pequenos relatos de observação de processos, de fatos, de experiências pessoais, mantendo as características do gênero, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP15', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Cantar cantigas e canções, obedecendo ao ritmo e à melodia.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP16', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Identificar e reproduzir, em  bilhetes, recados, avisos, cartas, e-mails, receitas (modo de fazer), relatos (digitais ou impressos), a formatação e diagramação específica de cada um desses gêneros.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP17', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Identificar e reproduzir, em relatos de experiências pessoais, a sequência dos fatos, utilizando expressões que marquem a passagem do tempo (“antes”, “depois”, “ontem”, “hoje”, “amanhã”, “outro dia”, “antigamente”, “há muito tempo” etc.), e o nível de informatividade necessário.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP11', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Escrever, em colaboração com os colegas e com a ajuda do professor, fotolegendas em notícias, manchetes e lides em notícias, álbum de fotos digital noticioso e notícias curtas para público infantil, digitais ou impressos, dentre outros gêneros do campo jornalístico, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP12', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Escrever, em colaboração com os colegas e com a ajuda do professor, slogans,* anúncios publicitários e textos de campanhas de conscientização destinados ao público* infantil, dentre outros gêneros do campo publicitário, considerando a situação comunicativa e o tema/ assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01LP21', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 1, 'Escrever, em colaboração com os colegas e com a ajuda do professor, listas de regras e regulamentos que organizam a vida na comunidade escolar, dentre outros gêneros do campo da atuação cidadã, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP18', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Planejar e produzir cartazes e folhetos para divulgar eventos da escola ou da comunidade, utilizando linguagem persuasiva e elementos textuais e visuais (tamanho da letra, leiaute, imagens) adequados ao gênero, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP19', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Planejar e produzir, em colaboração com os colegas e com a ajuda do professor, notícias curtas para público infantil,  para compor jornal falado que possa ser repassado oralmente ou em meio digital, em áudio ou vídeo, dentre outros gêneros do campo jornalístico, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP13', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Planejar, em colaboração com os colegas e com a ajuda do professor, slogans e* peça de campanha de conscientização destinada ao público infantil que possam ser repassados* oralmente por meio de ferramentas digitais, em áudio ou vídeo, considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP14', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Identificar e reproduzir, em fotolegendas de notícias, álbum de fotos digital noticioso, cartas de leitor (revista infantil), digitais ou impressos, a formatação e diagramação específica de cada um desses gêneros, inclusive em suas versões orais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP15', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Identificar a forma de composição de slogans publicitários.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP16', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Identificar e reproduzir, em anúncios publicitários e textos de campanhas de conscientização destinados ao público infantil (orais e escritos, digitais ou impressos), a formatação e diagramação específica de cada um desses gêneros, inclusive o uso de imagens.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP17', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Ler e compreender, em colaboração com os colegas e com a ajuda do professor, enunciados de tarefas escolares, diagramas, curiosidades, pequenos relatos de experimentos, entrevistas, verbetes de enciclopédia infantil, entre outros gêneros do campo investigativo, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP20', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Reconhecer a função de textos utilizados para apresentar informações coletadas em atividades de pesquisa (enquetes, pequenas entrevistas, registros de experimentações).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP21', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Explorar, com a mediação do professor, textos informativos de diferentes ambientes digitais de pesquisa, conhecendo suas possibilidades.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01LP22', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 1, 'Planejar e produzir, em colaboração com os colegas e com a ajuda do professor, diagramas, entrevistas, curiosidades, dentre outros gêneros do campo investigativo, digitais ou impressos, considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP22', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Planejar e produzir, em colaboração com os colegas e com a ajuda do professor, pequenos relatos de experimentos, entrevistas, verbetes de enciclopédia infantil, dentre outros gêneros do campo investigativo, digitais ou impressos, considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP23', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Planejar e produzir, com certa autonomia, pequenos registros de observação de resultados de pesquisa, coerentes com um tema investigado.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01LP23', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 1, 'Planejar e produzir, em colaboração com os colegas e com a ajuda do professor, entrevistas, curiosidades, dentre outros gêneros do campo investigativo, que possam ser repassados oralmente por meio de ferramentas digitais, em áudio ou vídeo, considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP24', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Planejar e produzir, em colaboração com os colegas e com a ajuda do professor, relatos de experimentos, registros de observação, entrevistas, dentre outros gêneros do campo investigativo, que possam ser repassados oralmente por meio de ferramentas digitais, em áudio ou vídeo, considerando a situação comunicativa e o tema/assunto/ finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01LP24', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 1, 'Identificar e reproduzir, em enunciados de tarefas escolares, diagramas, entrevistas, curiosidades, digitais ou impressos, a formatação e diagramação específica de cada um desses gêneros, inclusive em suas versões orais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP25', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Identificar e reproduzir, em relatos de experimentos, entrevistas, verbetes de enciclopédia infantil, digitais ou impressos, a formatação e diagramação específica de cada um desses gêneros, inclusive em suas versões orais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP26', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Ler e compreender, com certa autonomia, textos literários, de gêneros variados, desenvolvendo o gosto pela leitura.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP18', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Apreciar poemas e outros textos versificados, observando rimas, sonoridades, jogos de palavras, reconhecendo seu pertencimento ao mundo imaginário e sua dimensão de encantamento, jogo e fruição.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01LP25', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 1, 'Produzir, tendo o professor como escriba, recontagens de histórias lidas pelo professor, histórias imaginadas ou baseadas em livros de imagens, observando a forma de composição de textos narrativos (personagens, enredo, tempo e espaço).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP27', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Reescrever textos narrativos literários lidos pelo professor.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01LP26', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 1, 'Identificar elementos de uma narrativa lida ou escutada, incluindo personagens, enredo, tempo e espaço.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP28', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Reconhecer o conflito gerador de uma narrativa ficcional e sua resolução, além de palavras, expressões e frases que caracterizam personagens e ambientes.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12LP19', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 1, 2, 'Reconhecer, em textos versificados, rimas, sonoridades, jogos de palavras, palavras, expressões, comparações, relacionando-as com sensações e associações.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02LP29', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 2, 2, 'Observar, em poemas visuais, o formato do texto na página, as ilustrações e outros efeitos visuais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP06', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar a sílaba tônica em palavras, classificando-as em oxítonas, paroxítonas e proparoxítonas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP07', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar a função na leitura e usar na escrita ponto final, ponto de interrogação, ponto de exclamação e, em diálogos (discurso direto), dois-pontos e travessão.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP08', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar e diferenciar, em textos, substantivos e verbos e suas funções na oração: agente, ação, objeto da ação.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP06', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Identificar em textos e usar na produção textual a concordância entre substantivo ou pronome pessoal e verbo (concordância verbal).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP06', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Flexionar, adequadamente, na escrita e na oralidade, os verbos em concordância com pronomes pessoais/nomes sujeitos da oração.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP09', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar, em textos, adjetivos e sua função de atribuição de propriedades aos substantivos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP07', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Identificar em textos e usar na produção textual a concordância entre artigo, substantivo e adjetivo (concordância no grupo nominal).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP07', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Identificar, em textos, o uso de conjunções e a relação que estabelecem entre partes do texto: adição, oposição, tempo, causa, condição, finalidade.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP10', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Reconhecer prefixos e sufixos produtivos na formação de palavras derivadas de substantivos, de adjetivos e de verbos, utilizando-os para compreender palavras e para formar novas palavras.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP08', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Reconhecer e grafar, corretamente, palavras derivadas com os sufixos -agem, -oso, -eza, -izar/-isar (regulares morfológicas).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP08', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Diferenciar palavras primitivas, derivadas e compostas, e derivadas por adição de prefixo e de sufixo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP11', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Ler e compreender, com autonomia, textos injuntivos instrucionais (receitas, instruções de montagem etc.), com a estrutura própria desses textos (verbos imperativos, indicação de passos a ser seguidos) e mesclando palavras, imagens e recursos gráfico-visuais, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP09', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Ler e compreender, com autonomia, boletos, faturas e carnês, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero (campos, itens elencados, medidas de consumo, código de barras) e considerando a situação comunicativa e a finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP09', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Ler e compreender, com autonomia, textos instrucional de regras de jogo, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero e considerando a situação comunicativa e a finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP12', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Ler e compreender, com autonomia, cartas pessoais e diários, com expressão de sentimentos e opiniões, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero carta e considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP10', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Ler e compreender, com autonomia, cartas pessoais de reclamação, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero carta e considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP10', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Ler e compreender, com autonomia, anedotas, piadas e cartuns, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero e considerando a situação comunicativa e a finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP13', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Planejar e produzir cartas pessoais e diários, com expressão de sentimentos e opiniões, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções dos gêneros carta e diário e considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP11', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Planejar e produzir, com autonomia, cartas pessoais de reclamação, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero carta e com a estrutura própria desses textos (problema, opinião, argumentos), considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP11', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Registrar, com autonomia, anedotas, piadas e cartuns, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero e considerando a situação comunicativa e a finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP14', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Planejar e produzir textos injuntivos instrucionais, com a estrutura própria desses textos (verbos imperativos, indicação de passos a ser seguidos) e mesclando palavras, imagens e recursos gráfico-visuais, considerando a situação comunicativa e o tema/ assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP12', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Planejar e produzir, com autonomia, textos instrucionais de regras de jogo, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero e considerando a situação comunicativa e a finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP15', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Assistir, em vídeo digital, a programa de culinária infantil e, a partir dele, planejar e produzir receitas em áudio ou vídeo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP12', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Assistir, em vídeo digital, a programa infantil com instruções de montagem, de jogos e brincadeiras e, a partir dele, planejar e produzir tutoriais em áudio ou vídeo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP13', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Assistir, em vídeo  digital, a postagem de vlog infantil de críticas de brinquedos e livros de literatura infantil e, a partir dele, planejar e produzir resenhas digitais em áudio ou vídeo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP16', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar e reproduzir, em textos injuntivos instrucionais (receitas, instruções de montagem, digitais ou impressos), a formatação própria desses textos (verbos imperativos, indicação de passos a ser seguidos) e a diagramação específica dos textos desses gêneros (lista de ingredientes ou materiais e instruções de execução – \\\"modo de fazer\\\").,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP13', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Identificar e reproduzir, em textos injuntivos instrucionais (instruções de jogos digitais ou impressos), a formatação própria desses textos (verbos imperativos, indicação de passos a ser seguidos) e formato específico dos textos orais ou escritos desses gêneros (lista/ apresentação de materiais e instruções/passos de jogo).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP14', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Identificar e reproduzir, em textos de resenha crítica de brinquedos ou livros de literatura infantil, a formatação própria desses textos (apresentação e avaliação do produto).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP17', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar e reproduzir, em gêneros epistolares e diários, a formatação própria desses textos (relatos de acontecimentos, expressão de vivências, emoções, opiniões ou críticas) e a diagramação específica dos textos desses gêneros (data, saudação, corpo do texto, despedida, assinatura).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP18', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Ler e compreender, com autonomia, cartas dirigidas a veículos da mídia impressa ou digital (cartas de leitor e de reclamação a jornais, revistas) e notícias, dentre outros gêneros do campo jornalístico, de acordo com as convenções do gênero carta e considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP14', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Identificar, em notícias, fatos, participantes, local e momento/tempo da ocorrência do fato noticiado.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP15', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Ler/assistir e compreender, com autonomia, notícias, reportagens, vídeos  em vlogs argumentativos, dentre outros gêneros do campo político-cidadão, de acordo com as convenções dos gêneros e considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP19', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar e discutir o propósito do uso de recursos de persuasão (cores, imagens, escolha de palavras, jogo de palavras, tamanho de letras) em textos publicitários e de propaganda, como elementos de convencimento.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP15', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Distinguir fatos de opiniões/sugestões em textos (informativos, jornalísticos, publicitários etc.).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP16', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Comparar informações sobre um mesmo fato veiculadas em diferentes mídias e concluir sobre qual é mais confiável e por quê.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP20', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Produzir cartas dirigidas a veículos da mídia impressa ou digital (cartas do leitor ou de reclamação a jornais ou revistas), dentre outros gêneros do campo político-cidadão, com opiniões e críticas, de acordo com as convenções do gênero carta e considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP16', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Produzir notícias sobre fatos ocorridos no universo escolar, digitais ou impressas, para o jornal da escola, noticiando os fatos e seus atores e comentando decorrências, de acordo com as convenções do gênero notícia e considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP17', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Produzir roteiro para edição de uma reportagem digital sobre temas de interesse da turma, a partir de buscas de informações, imagens, áudios e vídeos na internet, de acordo com as convenções do gênero e considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP21', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Produzir anúncios publicitários, textos de campanhas de conscientização destinados ao público infantil, observando os recursos de persuasão utilizados nos textos publicitários e de propaganda  (cores, imagens, slogan, escolha de palavras, jogo de palavras, tamanho e tipo de letras, diagramação).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP22', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Planejar e produzir, em colaboração com os colegas, telejornal para público infantil com algumas notícias e textos de campanhas que possam ser repassados oralmente ou em meio digital, em áudio ou vídeo, considerando a situação comunicativa, a organização específica da fala nesses gêneros e o tema/assunto/ finalidade dos textos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP17', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Produzir jornais radiofônicos ou televisivos e entrevistas veiculadas em rádio, TV e na internet, orientando-se por roteiro ou texto e demonstrando conhecimento dos gêneros jornal falado/televisivo e entrevista.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP18', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Roteirizar, produzir e editar vídeo para  vlogs argumentativos sobre produtos de mídia para público infantil (filmes, desenhos  animados, HQs, games etc.), com base em conhecimentos sobre os mesmos, de acordo com as convenções do gênero e considerando a situação comunicativa e o tema/ assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP19', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Argumentar oralmente sobre acontecimentos de interesse social, com base em conhecimentos sobre fatos divulgados em TV, rádio, mídia impressa e digital, respeitando pontos de vista diferentes.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP23', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Analisar o uso de adjetivos em cartas dirigidas a veículos da mídia impressa ou digital (cartas do leitor ou de reclamação a jornais ou revistas), digitais ou impressas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP20', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Analisar a validade e força de argumentos em argumentações sobre produtos de mídia para público infantil (filmes, desenhos  animados, HQs, games etc.), com base em conhecimentos sobre os mesmos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP18', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Analisar o padrão entonacional e a expressão facial e corporal de âncoras de jornais radiofônicos ou televisivos e de entrevistadores/entrevistados.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP21', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Analisar o padrão entonacional, a expressão facial e corporal e as escolhas de variedade e registro linguísticos  de vloggers de vlogs opinativos ou argumentativos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP24', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Ler/ouvir e compreender, com autonomia, relatos de observações e de pesquisas em fontes de informações, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP19', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Ler e compreender textos expositivos de divulgação científica para crianças, considerando a situação comunicativa e o tema/ assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP22', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Ler e compreender verbetes de dicionário, identificando a estrutura, as informações gramaticais (significado de abreviaturas) e as informações semânticas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP20', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Reconhecer a função de gráficos, diagramas e tabelas em textos, como forma de apresentação de dados e informações.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP23', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Comparar informações apresentadas em gráficos ou tabelas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP25', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Planejar e produzir textos para apresentar resultados de observações e de pesquisas em fontes de informações, incluindo, quando pertinente, imagens, diagramas e gráficos ou tabelas simples, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP21', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Planejar e produzir textos sobre temas de interesse, com base em resultados de observações e pesquisas em fontes de informações impressas ou eletrônicas, incluindo, quando pertinente, imagens e gráficos ou tabelas simples, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP24', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Planejar e produzir texto sobre tema de interesse, organizando resultados de pesquisa em fontes de informação impressas ou digitais, incluindo imagens e gráficos ou tabelas, considerando a situação comunicativa e o tema/assunto do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP22', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Planejar e produzir, com certa autonomia, verbetes de enciclopédia infantil, digitais ou impressos, considerando a situação comunicativa e o tema/ assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP25', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Planejar e produzir, com certa autonomia, verbetes de dicionário, digitais ou impressos, considerando a situação comunicativa e o tema/assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP26', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Identificar e reproduzir, em relatórios de observação e pesquisa, a formatação e diagramação específica desses gêneros (passos ou listas de itens, tabelas, ilustrações, gráficos, resumo dos resultados), inclusive em suas versões orais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP26', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Utilizar, ao produzir o texto, conhecimentos linguísticos e gramaticais: regras sintáticas de concordância nominal e verbal, convenções de escrita de citações, pontuação (ponto final, dois-pontos, vírgulas em enumerações) e regras ortográficas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP23', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Identificar e reproduzir, em verbetes de enciclopédia infantil, digitais ou impressos, a formatação e diagramação específica desse gênero (título do verbete, definição, detalhamento, curiosidades), considerando a situação comunicativa e o tema/ assunto/finalidade do texto.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP27', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Utilizar, ao produzir o texto, recursos de coesão pronominal (pronomes anafóricos) e articuladores de relações de sentido (tempo, causa, oposição, conclusão, comparação), com nível adequado de informatividade.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP24', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Identificar e reproduzir, em seu formato, tabelas, diagramas e gráficos em relatórios de observação e pesquisa, como forma de apresentação de dados e informações.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP24', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Identificar funções do texto dramático (escrito para ser encenado) e sua organização por meio de diálogos entre personagens e marcadores das falas das personagens e de cena.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP25', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Criar narrativas ficcionais, com certa autonomia, utilizando detalhes descritivos, sequências de eventos e imagens apropriadas para sustentar o sentido do texto, e marcadores de tempo, espaço e de fala de personagens.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP26', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Ler e compreender, com certa autonomia, narrativas ficcionais que apresentem cenários e personagens, observando os elementos da estrutura narrativa: enredo, tempo, espaço, personagens, narrador e a construção do discurso indireto e discurso direto.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP27', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Ler e compreender, com certa autonomia, textos em versos, explorando rimas, sons e jogos de palavras, imagens poéticas (sentidos figurados) e recursos visuais e sonoros.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP28', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Declamar poemas, com entonação, postura e interpretação adequadas.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03LP27', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 3, 'Recitar cordel e cantar repentes e emboladas, observando as rimas e obedecendo ao ritmo e à melodia.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP25', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Representar cenas de textos dramáticos, reproduzindo as falas das personagens, de acordo com as rubricas de interpretação e movimento indicadas pelo autor.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP29', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Identificar, em narrativas, cenário, personagem central, conflito gerador, resolução e o ponto de vista com base no qual histórias são narradas, diferenciando narrativas em primeira e terceira pessoas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP30', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Diferenciar discurso indireto e discurso direto, determinando o efeito de sentido de verbos de enunciação e explicando o uso de variedades linguísticas no discurso direto, quando for o caso.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35LP31', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 3, 5, 'Identificar, em textos versificados, efeitos de sentido decorrentes do uso de recursos rítmicos e sonoros e de metáforas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP26', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Observar, em poemas concretos, o formato, a distribuição e a diagramação das letras do texto na página.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05LP28', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 5, 5, 'Observar, em ciberpoemas e minicontos infantis em mídia digital, os recursos multissemióticos presentes nesses textos digitais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04LP27', 'Ensino Fundamental – Anos Iniciais', 'Língua Portuguesa', 4, 4, 'Identificar, em textos dramáticos, marcadores das falas das personagens e de cena.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR11', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Criar e improvisar movimentos dançados de modo individual, coletivo e colaborativo, considerando os aspectos estruturais, dinâmicos e expressivos dos elementos constitutivos do movimento, com base nos códigos de dança.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR12', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Discutir, com respeito e sem preconceito, as experiências pessoais e coletivas em dança vivenciadas na escola, como fonte para a construção de vocabulários e repertórios próprios.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR13', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Identificar e apreciar criticamente diversas formas e gêneros de expressão musical, reconhecendo e analisando os usos e as funções da música em diversos contextos de circulação, em especial, aqueles da vida cotidiana.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR14', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Perceber e explorar os elementos constitutivos da música (altura, intensidade, timbre, melodia, ritmo etc.), por meio de jogos, brincadeiras, canções e práticas diversas de composição/criação, execução e apreciação musical.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR15', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Explorar fontes sonoras diversas, como as existentes no próprio corpo (palmas, voz, percussão corporal), na natureza e em objetos cotidianos, reconhecendo os elementos constitutivos da música e as características de instrumentos musicais variados.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR16', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Explorar diferentes formas de registro musical não convencional (representação gráfica de sons, partituras criativas etc.), bem como procedimentos e técnicas de registro em áudio e audiovisual, e reconhecer a notação musical convencional.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR17', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Experimentar improvisações, composições e sonorização de histórias, entre outros, utilizando vozes, sons corporais e/ou instrumentos musicais convencionais ou não convencionais, de modo individual, coletivo e colaborativo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR18', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Reconhecer e apreciar formas distintas de manifestações do teatro presentes em diferentes contextos, aprendendo a ver e a ouvir histórias dramatizadas e cultivando a percepção, o imaginário, a capacidade de simbolizar e o repertório ficcional.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR19', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Descobrir teatralidades na vida cotidiana, identificando elementos teatrais (variadas entonações de voz, diferentes fisicalidades, diversidade de personagens e narrativas etc.).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR20', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Experimentar o trabalho colaborativo, coletivo e autoral em improvisações teatrais e processos narrativos criativos em teatro, explorando desde a teatralidade dos gestos e das ações do cotidiano até elementos de diferentes matrizes estéticas e culturais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR21', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Exercitar a imitação e o faz de conta, ressignificando objetos e fatos e experimentando-se no lugar do outro, ao compor e encenar acontecimentos cênicos, por meio de músicas, imagens, textos ou outros pontos de partida, de forma intencional e reflexiva.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR22', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Experimentar possibilidades criativas de movimento e de voz na criação de um personagem teatral, discutindo estereótipos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR23', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Reconhecer e experimentar, em projetos temáticos, as relações processuais entre diversas linguagens artísticas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR24', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Caracterizar e experimentar brinquedos, brincadeiras, jogos, danças, canções e histórias de diferentes matrizes estéticas e culturais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR25', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Conhecer e valorizar o patrimônio cultural, material e imaterial, de culturas diversas, em especial a brasileira, incluindo-se suas matrizes indígenas, africanas e europeias, de diferentes épocas, favorecendo a construção de vocabulário e repertório relativos às diferentes linguagens artísticas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF15AR26', 'Ensino Fundamental – Anos Iniciais', 'Artes', 1, 5, 'Explorar diferentes tecnologias e recursos digitais (multimeios, animações, jogos  eletrônicos, gravações em áudio e vídeo, fotografia, softwares etc.) nos processos de criação artística.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF01', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Experimentar, fruir e recriar diferentes brincadeiras e jogos da cultura popular presentes no contexto comunitário e regional, reconhecendo e respeitando as diferenças individuais de desempenho dos colegas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF02', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Explicar, por meio de múltiplas linguagens (corporal, visual, oral e escrita), as brincadeiras e os jogos populares do contexto comunitário e regional, reconhecendo e valorizando a importância desses jogos e brincadeiras para suas culturas de origem.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF03', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Planejar e utilizar estratégias para resolver desafios de brincadeiras e jogos populares do contexto comunitário e regional, com base no reconhecimento das características dessas práticas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF04', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Colaborar na proposição e na produção de alternativas para a prática, em outros momentos e espaços, de brincadeiras e jogos e demais práticas corporais tematizadas na escola, produzindo textos (orais, escritos, audiovisuais) para divulgá-las na escola e na comunidade.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF05', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Experimentar e fruir, prezando pelo trabalho coletivo e pelo protagonismo, a prática de esportes de marca e de precisão, identificando os elementos comuns a esses esportes.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF06', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Discutir a importância da observação das normas e das regras dos esportes de marca e de precisão para assegurar a integridade própria e as dos demais participantes.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF07', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Experimentar, fruir e identificar diferentes elementos básicos da ginástica (equilíbrios, saltos, giros, rotações, acrobacias, com e sem materiais) e da ginástica geral, de forma individual e em pequenos grupos, adotando procedimentos de segurança.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF08', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Planejar e utilizar estratégias para a execução de diferentes elementos básicos da ginástica e da ginástica geral.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF09', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Participar da ginástica geral, identificando as potencialidades e os limites do corpo, e respeitando as diferenças individuais e de desempenho corporal.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF10', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Descrever, por meio de múltiplas linguagens (corporal, oral, escrita e audiovisual), as características dos elementos básicos da ginástica e da ginástica geral, identificando a presença desses elementos em distintas práticas corporais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF11', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Experimentar e fruir diferentes danças do contexto comunitário e regional (rodas cantadas, brincadeiras rítmicas e expressivas), e recriá-las, respeitando as diferenças individuais e de desempenho corporal.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF12EF12', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 1, 2, 'Identificar os elementos constitutivos (ritmo, espaço, gestos) das danças do contexto comunitário e regional, valorizando e respeitando as manifestações de diferentes culturas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF01', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Experimentar e fruir brincadeiras e jogos populares do Brasil e do mundo, incluindo aqueles de matriz indígena e africana, e recriá-los, valorizando a importância desse patrimônio histórico cultural.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF02', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Planejar e utilizar estratégias para possibilitar a participação segura de todos os alunos em brincadeiras e jogos populares do Brasil e de matriz indígena e africana.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF03', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Descrever, por meio de múltiplas linguagens (corporal, oral, escrita, audiovisual), as brincadeiras e os jogos populares do Brasil e de matriz indígena e africana, explicando suas características e a importância desse patrimônio histórico cultural na preservação das diferentes culturas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF04', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Recriar, individual e coletivamente, e experimentar, na escola e fora dela, brincadeiras e jogos populares do Brasil e do mundo, incluindo aqueles de matriz indígena e africana, e demais práticas corporais tematizadas na escola, adequando-as aos espaços públicos disponíveis.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF05', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Experimentar e fruir diversos tipos de esportes de campo e taco, rede/parede e invasão, identificando seus elementos comuns e criando estratégias individuais e coletivas básicas para sua execução, prezando pelo trabalho coletivo e pelo protagonismo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF06', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Diferenciar os conceitos de jogo e esporte, identificando as características que os constituem na contemporaneidade e suas manifestações (profissional e comunitária/lazer).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF07', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Experimentar e fruir, de forma coletiva, combinações de diferentes elementos da ginástica geral (equilíbrios, saltos, giros, rotações, acrobacias, com e sem materiais), propondo coreografias com diferentes temas do cotidiano.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF08', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Planejar e utilizar estratégias para resolver desafios na execução de elementos básicos de apresentações coletivas de ginástica geral, reconhecendo as potencialidades e os limites do corpo e adotando procedimentos de segurança.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF09', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Experimentar, recriar e fruir danças populares do Brasil e do mundo e danças de matriz indígena e africana, valorizando e respeitando os diferentes sentidos e significados dessas danças em suas culturas de origem.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF10', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Comparar e identificar os elementos constitutivos comuns e diferentes (ritmo, espaço, gestos) em danças populares do Brasil e do mundo e danças de matriz indígena e africana.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF11', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Formular e utilizar estratégias para a execução de elementos constitutivos das danças populares do Brasil e do mundo, e das danças de matriz indígena e africana.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF12', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Identificar situações de injustiça e preconceito geradas e/ou presentes no contexto das danças e demais práticas corporais e discutir alternativas para superá-las.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF13', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Experimentar, fruir e recriar diferentes lutas presentes no contexto comunitário e regional e lutas de matriz indígena e africana.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF14', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Planejar e utilizar estratégias básicas das lutas do contexto comunitário e regional e lutas de matriz indígena e africana experimentadas, respeitando o colega como oponente e as normas de segurança.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF35EF15', 'Ensino Fundamental – Anos Iniciais', 'Educação Física', 3, 5, 'Identificar as características das lutas do contexto comunitário e regional e lutas de matriz indígena e africana, reconhecendo as diferenças entre lutas e brigas e entre lutas e as demais práticas corporais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA06', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Construir fatos básicos da adição e utilizá-los em procedimentos de cálculo para resolver problemas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA07', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Compor e decompor número de até duas ordens, por meio de diferentes adições, com o suporte de material manipulável, contribuindo para a compreensão de características do sistema de numeração decimal e o desenvolvimento de estratégias de cálculo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA08', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Resolver e elaborar problemas de adição e de subtração, envolvendo números de até dois algarismos, com os significados de juntar, acrescentar, separar e retirar, com o suporte de imagens e/ou material manipulável, utilizando estratégias e formas de registro pessoais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA09', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Organizar e ordenar objetos familiares ou representações por figuras, por meio de atributos, tais como cor, forma e medida.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA10', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Descrever, após o reconhecimento e a explicitação de um padrão (ou regularidade), os elementos ausentes em sequências recursivas de números naturais, objetos ou figuras.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA11', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Descrever a localização de pessoas e de objetos no espaço em relação à sua própria posição, utilizando termos como à direita, à esquerda, em frente, atrás.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA12', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Descrever a localização de pessoas e de objetos no espaço segundo um dado ponto de referência, compreendendo que, para a utilização de termos que se referem à posição, como direita, esquerda, em cima, em baixo, é necessário explicitar-se o referencial.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA13', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Relacionar figuras geométricas espaciais (cones, cilindros, esferas e blocos retangulares) a objetos familiares do mundo físico.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA14', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Identificar e nomear figuras planas (círculo, quadrado, retângulo e triângulo) em desenhos apresentados em diferentes disposições ou em contornos de faces de sólidos geométricos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA15', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Comparar comprimentos, capacidades ou massas, utilizando termos como mais alto, mais baixo, mais comprido, mais curto, mais grosso, mais fino, mais largo, mais pesado, mais leve, cabe mais, cabe menos, entre outros, para ordenar objetos de uso cotidiano.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA16', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Relatar em linguagem verbal ou não verbal sequência de acontecimentos relativos a um dia, utilizando, quando possível, os horários dos eventos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA17', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Reconhecer e relacionar períodos do dia, dias da semana e meses do ano, utilizando calendário, quando necessário.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA18', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Produzir a escrita de uma data, apresentando o dia, o mês e o ano, e indicar o dia da semana de uma data, consultando calendários.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA19', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Reconhecer e relacionar valores de moedas e cédulas do sistema monetário brasileiro para resolver situações simples do cotidiano do estudante.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA20', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Classificar eventos envolvendo o acaso, tais como “acontecerá com certeza”, “talvez aconteça” e “é impossível acontecer”, em situações do cotidiano.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01MA21', 'Ensino Fundamental – Anos Iniciais', 'Matemática', 1, 1, 'Ler dados expressos em tabelas e em gráficos de colunas simples.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01GE06', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 1, 1, 'Descrever e comparar diferentes tipos de moradia ou objetos de uso cotidiano (brinquedos, roupas, mobiliários), considerando técnicas e materiais utilizados em sua produção.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01GE07', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 1, 1, 'Descrever atividades de trabalho relacionadas com o dia a dia da sua comunidade.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01GE08', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 1, 1, 'Criar mapas mentais e desenhos com base em itinerários, contos literários, histórias inventadas e brincadeiras.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01GE09', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 1, 1, 'Elaborar e utilizar mapas simples para localizar elementos do local de vivência, considerando referenciais espaciais (frente e atrás, esquerda e direita, em cima e embaixo, dentro e fora) e tendo o corpo como referência.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01GE10', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 1, 1, 'Descrever características de seus lugares de vivência relacionadas aos ritmos da natureza (chuva, vento, calor etc.).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01GE11', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 1, 1, 'Associar mudanças de vestuário e hábitos alimentares em sua comunidade ao longo do ano, decorrentes da variação de temperatura e umidade no ambiente.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02GE09', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 2, 2, 'Identificar objetos e lugares de vivência (escola e moradia) em imagens aéreas e mapas (visão vertical) e fotografias (visão oblíqua).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02GE10', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 2, 2, 'Aplicar princípios de localização e posição de objetos (referenciais espaciais, como frente e atrás, esquerda e direita, em cima e embaixo, dentro e fora) por meio de representações espaciais da sala de aula e da escola.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02GE11', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 2, 2, 'Reconhecer a importância do solo e da água para a vida, identificando seus diferentes usos (plantação e extração de materiais, entre outras possibilidades) e os impactos desses usos no cotidiano da cidade e do campo.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03GE07', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 3, 3, 'Reconhecer e elaborar legendas com símbolos de diversos tipos de representações em diferentes escalas cartográficas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03GE08', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 3, 3, 'Relacionar a produção de lixo doméstico ou da escola aos problemas causados pelo consumo excessivo e construir propostas para o consumo consciente, considerando a ampliação de hábitos de redução, reúso e reciclagem/descarte de materiais consumidos em casa, na escola e/ou no entorno.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03GE09', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 3, 3, 'Investigar os usos dos recursos naturais, com destaque para os usos da água em atividades cotidianas (alimentação, higiene, cultivo de plantas etc.), e discutir os problemas ambientais provocados por esses usos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03GE10', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 3, 3, 'Identificar os cuidados necessários para utilização da água na agricultura e na geração de energia de modo a garantir a manutenção do provimento de água potável.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03GE11', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 3, 3, 'Comparar impactos das atividades econômicas urbanas e rurais sobre o ambiente físico natural, assim como os riscos provenientes do uso de ferramentas e máquinas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04GE07', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 4, 4, 'Comparar as características do trabalho no campo e na cidade.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04GE08', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 4, 4, 'Descrever e discutir o processo de produção (transformação de matérias-primas), circulação e consumo de diferentes produtos.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04GE09', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 4, 4, 'Utilizar as direções cardeais na localização de componentes físicos e humanos nas paisagens rurais e urbanas.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04GE10', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 4, 4, 'Comparar tipos variados de mapas, identificando suas características, elaboradores, finalidades, diferenças e semelhanças.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04GE11', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 4, 4, 'Identificar as características das paisagens naturais e antrópicas (relevo, cobertura vegetal, rios etc.) no ambiente em que vive, bem como a ação humana na conservação ou degradação dessas áreas.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04GE12', 'Ensino Fundamental – Anos Iniciais', 'Geografia', 4, 4, 'DESCRIÇÃO NÃO ENCONTRADA - Preencher manualmente');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01HI06', 'Ensino Fundamental – Anos Iniciais', 'História', 1, 1, 'Conhecer as histórias da família e da escola e identificar o papel desempenhado por diferentes sujeitos em diferentes espaços.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01HI07', 'Ensino Fundamental – Anos Iniciais', 'História', 1, 1, 'Identificar mudanças e permanências nas formas de organização familiar.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01HI08', 'Ensino Fundamental – Anos Iniciais', 'História', 1, 1, 'Reconhecer o significado das comemorações e festas escolares, diferenciando-as das datas festivas comemoradas no âmbito familiar ou da comunidade.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02HI06', 'Ensino Fundamental – Anos Iniciais', 'História', 2, 2, 'Identificar e organizar, temporalmente, fatos da vida cotidiana, usando noções relacionadas ao tempo (antes, durante, ao mesmo tempo e depois).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02HI07', 'Ensino Fundamental – Anos Iniciais', 'História', 2, 2, 'Identificar e utilizar diferentes marcadores do tempo presentes na comunidade, como relógio e calendário.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02HI08', 'Ensino Fundamental – Anos Iniciais', 'História', 2, 2, 'Compilar histórias da família e/ou da comunidade registradas em diferentes fontes.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02HI09', 'Ensino Fundamental – Anos Iniciais', 'História', 2, 2, 'Identificar objetos e documentos pessoais que remetam à própria experiência no âmbito da família  e/ou da comunidade, discutindo as razões pelas quais alguns objetos são preservados e outros são descartados.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02HI10', 'Ensino Fundamental – Anos Iniciais', 'História', 2, 2, 'Identificar diferentes formas de trabalho existentes na comunidade em que vive, seus significados, suas especificidades e importância.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02HI11', 'Ensino Fundamental – Anos Iniciais', 'História', 2, 2, 'Identificar impactos no ambiente causados pelas diferentes formas de trabalho existentes na comunidade em que vive.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03HI06', 'Ensino Fundamental – Anos Iniciais', 'História', 3, 3, 'Identificar os registros de memória na cidade (nomes de ruas, monumentos, edifícios etc.), discutindo os critérios que explicam a escolha desses nomes.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03HI07', 'Ensino Fundamental – Anos Iniciais', 'História', 3, 3, 'Identificar semelhanças e diferenças existentes entre comunidades de sua cidade ou região, e descrever o papel dos diferentes grupos sociais que as formam.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03HI08', 'Ensino Fundamental – Anos Iniciais', 'História', 3, 3, 'Identificar modos de vida na cidade e no campo no presente, comparando-os com os do passado.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03HI09', 'Ensino Fundamental – Anos Iniciais', 'História', 3, 3, 'Mapear os espaços públicos no lugar em que vive (ruas, praças, escolas, hospitais, prédios da Prefeitura e da Câmara de Vereadores etc.) e identificar suas funções.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03HI10', 'Ensino Fundamental – Anos Iniciais', 'História', 3, 3, 'Identificar as diferenças entre o espaço doméstico, os espaços públicos e as áreas de conservação ambiental, compreendendo a importância dessa distinção.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03HI11', 'Ensino Fundamental – Anos Iniciais', 'História', 3, 3, 'Identificar diferenças entre formas de trabalho realizadas na cidade e no campo, considerando também o uso da tecnologia nesses diferentes contextos.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03HI12', 'Ensino Fundamental – Anos Iniciais', 'História', 3, 3, 'Comparar as relações de trabalho e lazer do presente com as de outros tempos e espaços, analisando mudanças e permanências.');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04HI06', 'Ensino Fundamental – Anos Iniciais', 'História', 4, 4, 'Identificar as transformações ocorridas nos processos de deslocamento das pessoas e mercadorias, analisando as formas de adaptação ou marginalização.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04HI07', 'Ensino Fundamental – Anos Iniciais', 'História', 4, 4, 'Identificar e descrever a importância dos caminhos terrestres, fluviais e marítimos para a dinâmica da vida comercial.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04HI08', 'Ensino Fundamental – Anos Iniciais', 'História', 4, 4, 'Identificar as transformações ocorridas nos meios de comunicação (cultura oral, imprensa, rádio, televisão, cinema, internet e demais tecnologias digitais de informação e comunicação) e discutir seus significados para os diferentes grupos ou estratos sociais.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04HI09', 'Ensino Fundamental – Anos Iniciais', 'História', 4, 4, 'Identificar as motivações dos processos migratórios em diferentes tempos e espaços e avaliar o papel desempenhado pela migração nas regiões de destino.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04HI10', 'Ensino Fundamental – Anos Iniciais', 'História', 4, 4, 'Analisar diferentes fluxos populacionais e suas contribuições para a formação da sociedade brasileira.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04HI11', 'Ensino Fundamental – Anos Iniciais', 'História', 4, 4, 'Analisar, na sociedade em que vive,  a existência ou não de mudanças associadas à migração (interna e internacional).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01ER01', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 1, 1, 'Identificar e acolher as semelhanças e diferenças entre o eu, o outro e o nós.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01ER02', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 1, 1, 'Reconhecer que o seu nome e o das demais pessoas os identificam e os diferenciam.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01ER03', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 1, 1, 'Reconhecer e respeitar as características físicas e subjetivas de cada um.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01ER04', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 1, 1, 'Valorizar a diversidade de formas de vida.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01ER05', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 1, 1, 'Identificar e acolher sentimentos, lembranças, memórias e saberes de cada um.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF01ER06', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 1, 1, 'Identificar as diferentes formas pelas quais as pessoas manifestam sentimentos, ideias, memórias, gostos e crenças em diferentes espaços.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02ER01', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 2, 2, 'Reconhecer os diferentes espaços de convivência.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02ER02', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 2, 2, 'Identificar costumes, crenças e formas diversas de viver em variados ambientes de convivência.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02ER03', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 2, 2, 'Identificar as diferentes formas de registro das memórias pessoais, familiares e escolares (fotos, músicas, narrativas, álbuns...).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02ER04', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 2, 2, 'Identificar os símbolos presentes nos variados espaços de convivência.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02ER05', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 2, 2, 'Identificar, distinguir e respeitar símbolos religiosos de distintas manifestações, tradições e instituições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02ER06', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 2, 2, 'Exemplificar alimentos considerados sagrados por diferentes culturas, tradições e expressões religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF02ER07', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 2, 2, 'Identificar significados atribuídos a alimentos em diferentes manifestações e tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03ER01', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 3, 3, 'Identificar e respeitar os diferentes espaços e territórios religiosos de diferentes tradições e movimentos religiosos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03ER02', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 3, 3, 'Caracterizar os espaços e territórios religiosos como locais de realização das práticas celebrativas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03ER03', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 3, 3, 'Identificar e respeitar práticas celebrativas (cerimônias, orações, festividades, peregrinações, entre outras) de diferentes tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03ER04', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 3, 3, 'Caracterizar as práticas celebrativas como parte integrante do conjunto das manifestações religiosas de diferentes culturas e sociedades.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03ER05', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 3, 3, 'Reconhecer as indumentárias (roupas, acessórios, símbolos, pinturas corporais) utilizadas em diferentes manifestações e tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF03ER06', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 3, 3, 'Caracterizar as indumentárias como elementos integrantes das identidades religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04ER01', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 4, 4, 'Identificar ritos presentes no cotidiano pessoal, familiar, escolar e comunitário.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04ER02', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 4, 4, 'Identificar ritos e suas funções em diferentes manifestações e tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04ER03', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 4, 4, 'Caracterizar ritos de iniciação e de passagem em diversos grupos religiosos (nascimento, casamento e morte).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04ER04', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 4, 4, 'Identificar as diversas formas de expressão da espiritualidade (orações, cultos, gestos, cantos, dança, meditação) nas diferentes tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04ER05', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 4, 4, 'Identificar representações religiosas em diferentes expressões artísticas (pinturas, arquitetura, esculturas, ícones, símbolos, imagens), reconhecendo-as como parte da identidade de diferentes culturas e tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04ER06', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 4, 4, 'Identificar nomes, significados e representações de divindades nos contextos familiar e comunitário.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF04ER07', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 4, 4, 'Reconhecer e respeitar as ideias de divindades de diferentes manifestações e tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05ER01', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 5, 5, 'Identificar e respeitar acontecimentos sagrados de diferentes culturas e tradições religiosas como recurso para preservar a memória.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05ER02', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 5, 5, 'Identificar mitos de criação em diferentes culturas e tradições religiosas.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05ER03', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 5, 5, 'Reconhecer funções e mensagens religiosas contidas nos mitos de criação (concepções de mundo, natureza, ser humano, divindades, vida e morte).,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05ER04', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 5, 5, 'Reconhecer a importância da tradição oral para preservar memórias e acontecimentos religiosos.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05ER05', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 5, 5, 'Identificar elementos da tradição oral nas culturas e religiosidades indígenas, afro-brasileiras, ciganas, entre outras.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05ER06', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 5, 5, 'Identificar o papel dos sábios e anciãos na comunicação e preservação da tradição oral.,');
INSERT INTO habilidades_bncc (codigo_bncc, etapa, componente, ano_inicio, ano_fim, descricao) VALUES ('EF05ER07', 'Ensino Fundamental – Anos Iniciais', 'Ensino Religioso', 5, 5, 'Reconhecer, em textos orais, ensinamentos relacionados a modos de ser e viver.');

COMMIT;
